version: '3.8'

services:
  app:
    build: .
    container_name: drivers_license_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:

      MY_SECRET_KEY: ${MY_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
    entrypoint: ["flask", "run", "--host=0.0.0.0", "--port=8000"]

    networks:
     - net 

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf 
    networks:
      - net 

networks:
  net:
    driver: bridge  # Bridge ტიპის ქსელი, რომელიც გამოიყენება კონტეინერების იზოლაციისთვის.

volumes:
  mysql_data: